### ISSUE TITLE
Prompt on FAB Menu position miss match

### ISSUE THREAD

**Issue by supportreq** [sjwall/MaterialTapTargetPrompt#15]
I am using the Clans' FAB Button library for my application. https://github.com/Clans/FloatingActionButton.

mFabPrompt = new MaterialTapTargetPrompt.Builder(MainActivityFloat.this)
                .setTarget(findViewById(R.id.multiple_actions))
The generated output is:

![fab](https://cloud.githubusercontent.com/assets/4680404/19030492/d091f2f0-896b-11e6-90a4-a96c187f1ff5.jpg)

The FAB buttons are being displayed perfectly except the menu..
Please advice..

**Comment by sjwall** [comment]
Hi, thanks letting me know about the issue, I shall do some testing with Clans' FAB Button library on the sample app and see if I can replicate it.

**Comment by sjwall** [comment]
Hi @supportreq I can replicate the issue in the sample app when using _com.github.clans.fab.FloatingActionMenu_. 
It works fine with _com.github.clans.fab.FloatingActionButton_ on its own.
I am working on a fix

**Comment by sjwall** [comment]
Added a new method to the `Builder`, `setTargetRenderView(View)`. It can be used as shown below to fix the positioning issue and will be released in the next update:

```Java
// Get the menu view that is around the FAB button
FloatingActionMenu menu = (FloatingActionMenu) findViewById(R.id.menu);
new MaterialTapTargetPrompt.Builder(this)
                // The Clans FAB library has a ImageView that is used to display the +,
                // so use this as the target
                .setTarget(menu.getMenuIconView())
                 // Set the menu as the view to render so that the FAB background is displayed
                .setTargetRenderView(menu)
// More setup code goes here
                 .show();
```

In the sample app the above displays like this:
<img src="https://cloud.githubusercontent.com/assets/16527946/19601603/e51f89e6-97a1-11e6-9128-e99ff9450631.png" width="250px">

There is still an issue when the prompt is displayed and the Clans FAB menu is already displayed:
<img src="https://cloud.githubusercontent.com/assets/16527946/19601754/7e0ac634-97a2-11e6-9bff-699c6d77535c.png" width="250px"> I will fix this issue in a future update

**Comment by sjwall** [comment]
The fix has been released in v1.5.0 and issue #18 has been raised to cover the incorrect positioning when the fab menu is open (this is down to the + image being rotated)

**Comment by supportreq** [comment]
@sjwall i am still getting the error on my app... the position of the menu is still incorrect..

please advice..

**Comment by sjwall** [comment]
Are you using `setTarget(menu.getMenuIconView())` and `setTargetRenderView(menu)` as shown in my [comment above](https://github.com/sjwall/MaterialTapTargetPrompt/issues/15#issuecomment-255391451)?

**Comment by supportreq** [comment]
@sjwall thanks it works perfectly fine!!
