### ISSUE TITLE
java.lang.NoClassDefFoundError: uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder

### ISSUE THREAD

**Issue by ImanX** [sjwall/MaterialTapTargetPrompt#16]
hi ! 
this issues in Android 4.0 to low , but not problem in android 5.0 
please help me !!!

**Comment by sjwall** [comment]
Hey, NoClassDefFoundError means that the Builder class is there when the class using it was compiled but not when it executed.

From the [Java docs](https://docs.oracle.com/javase/7/docs/api/java/lang/NoClassDefFoundError.html)
> The searched-for class definition existed when the currently executing class was compiled, but the definition can no longer be found.

With it working for you in Android 5.0 I would make a guess at it not bundling the library in the apk for lower releases. This may be an issue with your build.gradle.

Hope this helps, let me know if you get anywhere or need more help

**Comment by sjwall** [comment]
No response for a month so assuming it is fixed. Please reopen if not

**Comment by ptahsohn** [comment]
Still facing the same problem, but not sure what could be the issue with the build.gradle file.

**Comment by hukumsingh87** [comment]
Application extends MultiDexApplication

and
compile 'com.android.support:multidex:1.0.1'
