### ISSUE TITLE
Grow outer circle / force side (instead of center) positioning?

### ISSUE THREAD

**Issue by mstawick** [sjwall/MaterialTapTargetPrompt#41]
This screenshot best describes my problem:
https://goo.gl/photos/qHuLLGe1hvqjvBrL6

When focal is pulsating, it's touching outer circle. And also it would look better if the outer circle was stuck right-side, instead of being centered.

Is there some smart way of forcing it to stick to side? 

Many many thanks for a great library!

**Comment by sjwall** [comment]
It looks like the outer circle isn't positioned correctly. By default it should have 40dp padding between the 2 circles, which then means that the pulsing remains within the outer circle. I will investigate and fix this.

With regards to forcing it to stick to the side do you mean that the outer circle centre point is the same as the inner circles?

Thanks

**Comment by mstawick** [comment]
Thanks for getting back on this!

Re 1) You're right, it's actually not touching when I look close. But circles get really close to each other. It would be nice if we could configure this padding (I think when it's stretched pulsing, there's only ~4dp left in my case). Or maybe manually override big circle radius like we can with inner circle. 

Ref 2) So this one I consider 'being stuck to side' - I don't know how to better call it:
https://goo.gl/photos/Vre5SjNZznm7qQtt6
I understand that positioning of circles can be really tricky. 

But anyway, thanks for this great library!

**Comment by sjwall** [comment]
Re 1) The padding is currently configurable by using `setTextPadding` but it appears to not be applied correctly when the inner circle is a lot bigger than the default. Currently looking in to this.

Re 2) I understand now, I will get it to appear something similar to what it does in your first screenshot

**Comment by sjwall** [comment]
I have got it using a smaller background when it is halfway down the side, still working on making the background circle size and position optimised so that the focal pulsing doesn't go over the edge

**Comment by sjwall** [comment]
Both issues should now be fixed in release v1.9. Please close this issue if this fixes it. Thanks

**Comment by mstawick** [comment]
Thanks! I'll test it tomorrow and get back with feedback. Again - thanks.

**Comment by mstawick** [comment]
I've tested with version 1.9. The original cases are solved - looks very nice now, but there seems to be a regression for others that used to work just fine. Here are examples:

a) https://goo.gl/photos/YmMqaQ7z6Pguyfcx5 
Incorrect padding. I haven't changed defaults (maybe I should try and see what happens). I think it's combination of target being small and close to screen edge. I have same size target, but at the center of the screen, which works fine.

b) https://goo.gl/photos/aRHpV4DspLutKL5T8
Focal going out of bounds of circle (captured on screenshot this time).

**Comment by sjwall** [comment]
It's a lot better now, still not perfect in some scenarios.  Released in v1.9.1

**Comment by mstawick** [comment]
Perfect, all my guides render nicely with latest changes. This fixes my issue - I will close it now. Thank you very much!
